spring:
  datasource:
#    url: jdbc:h2:~/Desktop/study/h2db/jpashop
#    url: jdbc:h2:~/Desktop/study/SPAMMY_PLAYGROUND/inflearn/inflearn-springboot+JPA_1/db/jpashop
    url: jdbc:h2:tcp://localhost/~/Desktop/study/SPAMMY_PLAYGROUND/inflearn/inflearn-springboot+JPA_2/db/jpashop

    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

