CREATE TABLE mvc_board(
	board_no NUMBER PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	content VARCHAR(2000) NULL,
	writer VARCHAR(100) NOT NULL,
	reg_date TIMESTAMP DEFAULT SYSDATE,
	view_cnt NUMBER DEFAULT 0
);

CREATE SEQUENCE wow_board
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOCYCLE
NOCACHE;
